/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial1g2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testCalcularTotalImpuestos() {
        assertEquals(735900, App.calcularTotalImpuestos("90", 15000000));
        assertEquals(924840, App.calcularTotalImpuestos("00", 18000000));
        assertEquals(1594750, App.calcularTotalImpuestos("20", 25000000));
    }
}
